### ISSUE TITLE
The 28x28 gridworld file (dataset for training) corrupted?

### ISSUE THREAD

**Issue by kentsommer** [zuoxingdong/VIN_PyTorch_Visdom#2]
I receive the following error when trying to train on the 28x28 gridworld dataset:

```cPickle.UnpicklingError: BINUNICODE pickle has negative byte count```

I have tried re-downloading (which did not fix it), and have confirmed both the 16x16 and 8x8 versions work fine.

**Comment by avivt** [comment]
OK, let me check it out.

**Comment by kentsommer** [comment]
@avivt 

I was able to generate my own dataset. So, my issue is fixed. However, I'll leave this open as I'm sure at some point someone would like to use the included 28x28 and a fix here would be useful.

**Comment by zuoxingdong** [comment]
@kentsommer Sorry for the late reply. I've tried again to re-clone whole repo to test it, however, I am not able to reproduce this error. Are you using Anaconda, and with Python 3.x ? Maybe it is also related to your pickle version.

**Comment by kentsommer** [comment]
@zuoxingdong 

No, I'm was virtualenv and Python 2.7 which after trying 3.x seems to fix the issue... Odd that the only issue with 2.7 and > is the loading issue on 28x28. Regardless this is working if using Python 3.x, closing out.
